sources:
  - abbr: BFRD
    name: Black Flag Reference Document
    version: "1.0"
    url: https://bfrd.net/
    license: Open RPG Creative License (ORC)
    inputRoot: input/bfrd
  - abbr: ToVPG1
    name: Руководство для игрока том 1
    version: "1.0"
    url: https://localhost/
    license: Материалы для первичного ознакомления
    inputRoot: input/tovpg1
  - abbr: ToVPG2
    name: Руководство для игрока том 2
    version: "1.0"
    url: https://localhost/
    license: Материалы для первичного ознакомления
    inputRoot: input/tovpg2